version: "3.7"

services:
  app:
    container_name: "${APP_ID}-app"
    build: .
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./storage:/app/storage:cached
      - ./app:/app/app:cached
      - ./bootstrap:/app/bootstrap:cached
      - ./config:/app/config:cached
      - ./database:/app/database:cached
      - ./public:/app/public:cached
      - ./resources:/app/resources:cached
      - ./routes:/app/routes:cached
      - ./tests:/app/tests:cached
      - ./vendor:/app/vendor:cached
      - ./node_modules:/app/node_modules:cached

  worker:
    container_name: "${APP_ID}-worker"
    build: .
    volumes:
      - ./storage:/app/storage:cached
      - ./app:/app/app:cached
      - ./bootstrap:/app/bootstrap:cached
      - ./config:/app/config:cached
      - ./database:/app/database:cached
      - ./resources/lang:/app/resources/lang:cached
      - ./routes:/app/routes:cached
      - ./vendor:/app/vendor:cached

  postgres:
    container_name: "${APP_ID}-postgres"
    command: "-p ${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: "pg_isready -p ${DB_PORT} -U ${DB_USERNAME}"

  redis:
    container_name: "${APP_ID}-redis"
    command: "--port ${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: "redis-cli -p ${REDIS_PORT} ping"
