version: "3.7"

services:
  app:
    command: [
      "supervisord",
      "&& php artisan config:cache",
      "&& php artisan route:cache",
      # "&& php artisan view:cache"
    ]
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "https://${VIRTUAL_HOST}"
      DB_PORT: 5432
      REDIS_PORT: 6379
      LOG_CHANNEL: stderr
      # PHP-FPM optimizations
      # fpm.pool.pm: 'dynamic'
      # fpm.pool.pm.max_children: '200'
      # fpm.pool.pm.start_servers: '20'
      # fpm.pool.pm.min_spare_servers: '20'
      # fpm.pool.pm.max_spare_servers: '100'
      # fpm.pool.pm.max_requests: '1000'
    networks:
      - app
      - proxy
    deploy:
      replicas: 2

  worker:
    networks:
      - app
    deploy:
      replicas: 2

  postgres:
    networks:
      - app
    healthcheck:
      test: "pg_isready -U ${DB_USERNAME}"
    deploy:
      mode: global

  redis:
    networks:
      - app
    healthcheck:
      test: "redis-cli ping"
    deploy:
      mode: global

networks:
  app:
    name: "${APP_ID}"
  proxy:
    external: true
    name: "${NETWORK_PROXY}"
