version: "3.7"

services:
  app:
    image: "${IMAGE}"
    user: "1000:1000"
    env_file:
      - .env
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    labels:
      - "${APP_ID}.app"
    healthcheck:
      test: curl -f http://localhost || exit 1

  worker:
    image: "${IMAGE}"
    user: "1000:1000"
    env_file:
      - .env
    labels:
      - "${APP_ID}.worker"
    entrypoint: supervisord
    command: -c /app/supervisord.conf

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
    labels:
      - "${APP_ID}.postgres"
      - "${APP_ID}.db"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.8
    labels:
      - "${APP_ID}.redis"
    volumes:
      - redis:/data

volumes:
  postgres:
    name: "${APP_ID}-postgres"
  redis:
    name: "${APP_ID}-redis"
